# Default values for jats-validator.
ingress:
  host: basex-validator--staging.elifesciences.org
  basex-validator:
    path: /

basex-validator:
  image:
    repository: elifesciences/basex-validator
    tag: latest
    pullPolicy: Always
  port: 80
  replicaCount: 1
