# Default values for jats-validator.
ingress:
  host: basex-validator--staging.elifesciences.org
  basexValidator:
    path: /
    pathType: ImplementationSpecific

basexValidator:
  image:
    repository: elifesciences/basex-validator
    tag: latest
    pullPolicy: Always
  port: 8984
  replicaCount: 1
  maxUnavailable: 1
