{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "basex-validator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "basex-validator.name" . }}
    helm.sh/chart: {{ include "basex-validator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.basexValidator.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: {{ .Values.ingress.basexValidator.path }}
          {{- if and .Values.ingress.basexValidator.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
          pathType: {{ .Values.ingress.basexValidator.pathType }}
          {{- end }}
          backend:
            {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            service:
              name: {{ include "basex-validator.fullname" . }}
              port:
                number: {{ .Values.basexValidator.port }}
            {{- else }}
            serviceName: {{ include "basex-validator.fullname" . }}
            servicePort: {{ .Values.basexValidator.port }}
            {{- end }}
