apiVersion: v1
kind: Service
metadata:
  name: {{ include "basex-validator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "basex-validator.name" . }}
    helm.sh/chart: {{ include "basex-validator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: basex-validator
spec:
  type: ClusterIP
  ports:
    - port: 8984
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "basex-validator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: basex-validator