name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: Lint and Validate
        uses: elifesciences/helm-validator-action@v1
        with:
          chartPath: 'helm/basex-validator'
