name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checking formula for formatting issues
        run: |
          docker run --rm -it -v $GITHUB_WORKSPACE/helm/basex-validator:/formula:ro -v $GITHUB_WORKSPACE/out:/out:rw alpine/helm lint /formula
      - name: Creating template from formula
        run: |
          docker run --rm -it -v $GITHUB_WORKSPACE/helm/basex-validator:/formula:ro -v $GITHUB_WORKSPACE/out:/out:rw alpine/helm template basex-validator--ci /formula --output-dir /out
      - name: Validating formula
        run: |
          docker run -it -v $GITHUB_WORKSPACE/out/basex-validator/templates:/templates:ro ghcr.io/yannh/kubeconform -kubernetes-version 1.19.0 -summary -strict -output json /templates/
